### ISSUE TITLE
Cannot Read from python

### ISSUE THREAD

**Issue by ulisesbussi** [MarvelmindRobotics/marvelmind.py#3]
First of all, i want to give you the thanks for spending time reading me. 
Second, I will ask for forgiveness in advance for my english and writting. 

I'm trying to use this python script, but no example run, besides the fact that the library has some  indentation errors that i've corrected, but if I try to read a line of information, it allways returns 0's

if I try to connect via serial port connection with python an read lines i get this:

b'\xb3\x02\x00\x00\x1f\xfd\xff\xff\x00\x00\x00\x00\x00\x0c\x88\xff\xff\xffS\xfd\xff\xff\x00\x00\x00\x00\x00\x0f\x08\x03\x00\x00V\x00\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x9b\xdd\xffG\x12\x009\x04\r'

getting inside the library, I see that the all the code depends on finding b'\xff\x47' on the readed data,  that never appears

last of all I've tryed to run the example code with debug mode and get these three line repeated alterating the number of times that they appear:

>> Found USNAV beacon packet header at offset 0
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Message length:  71

sometimes something like
>> Found USNAV beacon packet header at offset 0
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Message length:  71
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00
Message length:  71
Hedge 0: X: 0 m, Y: 0 m, Z: 0 m, Angle: 0 at time T: 0.00

and goes on and on...

If you have some doubts or i'm missing some fundamental or required information please let me know!

**Comment by smoker771** [comment]
Received data don't contain Marvelmind data packets. It looks like received on wrong baud rate or from wrong serial port.
Printing messages with zero time and data was fixed in one of last updates.
